### ISSUE TITLE
Lookup items are hard to read with new lookup window implementation

### ISSUE THREAD

**Issue by auduchinok** [OlyaB/GreyTheme#3]
Grey:
<img width="384" alt="Screenshot 2019-06-10 at 21 18 43" src="https://user-images.githubusercontent.com/3923587/59216923-72104d80-8bc5-11e9-8c71-ac074cb4bea7.png">

IntelliJ:
<img width="353" alt="Screenshot 2019-06-10 at 21 19 01" src="https://user-images.githubusercontent.com/3923587/59216924-72104d80-8bc5-11e9-8dd4-3188dc2d8d98.png">

**Comment by OlyaB** [comment]
Thanks, fixed
